apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAB0s/dBOyxH59ERuV0QAh1ktY8v8bXgz4wf8Al2XhkN17lKm1TIN3lV2ezIwDGsYF+7YfMy0Niwd0GcPu9FoeT78MnEias9RWVjDSMcEBnVZr4xOFUwgVsXoKjYFtZnyoqv/MEXWf8b1qYMgvOZm75A+IGnDkMSQ60io4VFD2OogMJAzfUCg4CTdO62ptcq+tB/tltxNKcNha1pRbUJPtvMl/f9SquQw3jpqL8bMSuL9SzruLIyak7950tBrjcooJb2JNoYgxgXPGHwBG73SjpCvioACTNey3y0NryuwmoWonLzAjDANgtIytxE81CVdWeRx1b0yOfWgmvxbpVpFeMlZ5Bodyov7WPTZpuZfVvbDWMWWizW/qdy3HzhLLFH24FWZGil09GoHXISTcbrg/pIiIL4vTCCnT3p8agcjtB1bt1KUYiNeM5kJdomKsQxqme78Qpuz2D3IpYJ5qYrRGTLjHHw/t6SifVhqrIcCt0Guu34UuymhSvBICNvBDEI88kCD7hqxbeedIDRFmBtJFlJp+rvzeWgnQLErlgCBkqgJ6bJsdZlpKElEHJzt3cD66ackueRmHO22kmovMa36pXvscJ87k04q2SEyxgHk7K3OSJs/ZCPnT70mPyWEhXZPUfLQdUezx0j5IkFLFHvAAp6oI4Yg09WTvQ+vWS/hY2qriRtpe3iQlx4NipWDYrWyyR4gcXi/zEUbbInznF12agvGhOKte8/XtpJI5YEZJIfQ8jxyYDm6ai
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

